# Generated by Django 3.1.4 on 2021-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_question',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
