# Generated by Django 3.1.4 on 2021-01-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
