# Generated by Django 3.1.4 on 2021-01-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210113_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
