# Generated by Django 3.1.4 on 2021-01-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210113_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.question'),
        ),
    ]
