# Generated by Django 3.1.4 on 2021-02-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210204_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
