# Generated by Django 3.1.4 on 2021-02-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20210204_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.question'),
        ),
    ]
