# Generated by Django 3.1.5 on 2021-02-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20210204_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questin',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_question',
            new_name='answer',
        ),
    ]
